[variables]
NIXPACKS_PHP_ROOT_DIR = "langlearn-api"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.build]
cmds = [
  "cd langlearn-api && composer install --no-dev --optimize-autoloader",
  "cd langlearn-api && cp .env.example .env",
  "cd langlearn-api && touch database/database.sqlite",
  "cd langlearn-api && php artisan key:generate --force",
  "cd langlearn-api && php artisan migrate --force",
  "cd langlearn-api && php artisan db:seed --force"
]

[start]
cmd = "cd langlearn-api && mkdir -p storage/firebase && echo \"$FIREBASE_CREDENTIALS_JSON\" > storage/firebase/firebase_credentials.json && php artisan serve --host=0.0.0.0 --port=$PORT"