[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.build]
cmds = [
  "rm -rf bootstrap/cache/*.php",
  "composer install --no-dev --optimize-autoloader --no-scripts",
  "cp .env.example .env",
  "mkdir -p database",
  "touch database/database.sqlite"
]

[phases.start]
cmd = "bash start.sh"