[build]
builder = "NIXPACKS"

[build.nixpacksplan]
providers = ["php"]
buildCommand = "cd langlearn-api && composer install --no-dev --optimize-autoloader"

[deploy]
startCommand = "cd langlearn-api && php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
NIXPACKS_PHP_ROOT_DIR = "langlearn-api"